// Mocks generated by Mockito 5.4.4 from annotations
// in meme_editor_app_offline_first_flutter_application/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:meme_editor_app_offline_first_flutter_application/data/repo/meme_repository_impl.dart'
    as _i3;
import 'package:meme_editor_app_offline_first_flutter_application/domain/entities/meme.dart'
    as _i6;
import 'package:meme_editor_app_offline_first_flutter_application/domain/repo/meme_repository.dart'
    as _i2;
import 'package:meme_editor_app_offline_first_flutter_application/domain/usecase/get_memes.dart'
    as _i4;
import 'package:meme_editor_app_offline_first_flutter_application/domain/usecase/save_image_usecase.dart'
    as _i7;
import 'package:meme_editor_app_offline_first_flutter_application/domain/usecase/share_image_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMemeRepository_0 extends _i1.SmartFake
    implements _i2.MemeRepository {
  _FakeMemeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemeRepositoryImpl_1 extends _i1.SmartFake
    implements _i3.MemeRepositoryImpl {
  _FakeMemeRepositoryImpl_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMemes].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMemes extends _i1.Mock implements _i4.GetMemes {
  MockGetMemes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MemeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MemeRepository);

  @override
  _i5.Future<List<_i6.MemeEntity>> call({bool? fromCache = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#fromCache: fromCache},
        ),
        returnValue: _i5.Future<List<_i6.MemeEntity>>.value(<_i6.MemeEntity>[]),
      ) as _i5.Future<List<_i6.MemeEntity>>);
}

/// A class which mocks [SaveImageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveImageUsecase extends _i1.Mock implements _i7.SaveImageUsecase {
  MockSaveImageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MemeRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemeRepositoryImpl_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemeRepositoryImpl);

  @override
  _i5.Future<bool> call(_i8.Uint8List? imageBytes) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [imageBytes],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [ShareImageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareImageUsecase extends _i1.Mock implements _i9.ShareImageUsecase {
  MockShareImageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MemeRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemeRepositoryImpl_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemeRepositoryImpl);

  @override
  _i5.Future<void> call(_i8.Uint8List? imageBytes) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [imageBytes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
